### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by usernamehw** [fabiospampinato/vscode-highlight#25]
I thought I can ignore it, but it just completely trashed dev console with message:
```
  ERR Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
	at Object.decorateLines (C:\Users\al\.vscode\extensions\fabiospampinato.vscode-highlight-1.3.3\out\extension.js:1:2956)
	at Object.decorate (C:\Users\al\.vscode\extensions\fabiospampinato.vscode-highlight-1.3.3\out\extension.js:1:4142)
	at onChanges (C:\Users\al\.vscode\extensions\fabiospampinato.vscode-highlight-1.3.3\out\extension.js:1:4008)
	at e.fire (c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at e.$acceptModelChanged (c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:524:279)
	at t._doInvokeHandler (c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:118)
	at t._invokeHandler (c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:744)
	at t._receiveRequest (c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:322)
	at t._receiveOneMessage (c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:155)
	at c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Users\al\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

Extension version: 1.3.3
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

**Comment by fabiospampinato** [comment]
🤔 We are retrieving the editor's id in a few places (`textEditor['id']`), I guess sometimes that's not set, after all that's not even a documented property. Maybe as a quick workaround we could replace all those `textEditor['id']` with a `getTextEditorId` function or something, that returns an empty string in case there's no actual id.

**Comment by fabiospampinato** [comment]
I'll be happy to consider a PR for this 👍
